import type { Item } from "./components/ItemCard/ItemCard";

export const data: Item[] = [
  {
    key: "sortabase",
    type: "work",
    iconName: "sortabase.png",
    description: "Founded a startup with a friend, working full-time",
    endDate: "present",
    startDate: "2021-11-01",
    title: "Sortabase",
    location: "Toronto",
    position: "Cofounder, Full-Stack Engineer",
    siteUrl: "https://sortabase.com",
    tools: ["Next.js", "Vercel", "AWS", "SASS", "TypeScript", "React", "Figma", "Ant Design", "Sendgrid"],
  },
  {
    key: "threekit-ux-consultant",
    type: "work",
    iconName: "threekit.png",
    description: "Founded a startup with a friend, working full-time",
    endDate: "2021-10-15",
    startDate: "2021-05-01",
    title: "Threekit",
    location: "Toronto",
    position: "UX Consultant",
    siteUrl: "https://sortabase.com",
    figmaUrl: "https://www.figma.com/community/file/1027317639278516141/Threekit-React-Dev-Kit-Design-System",
    tools: ["React", "Figma", "Illustrator", "Sketchup"],
  },
  {
    key: "threekit-ux-designer",
    type: "work",
    iconName: "threekit.png",
    description: "Founded a startup with a friend, working full-time",
    endDate: "2021-05-01",
    startDate: "2020-04-01",
    title: "Threekit",
    location: "Ottawa",
    position: "UX Designer",
    siteUrl: "https://sortabase.com",
    tools: ["Figma", "Gitlab", "Jira"],
  },
  {
    key: "threekit-ux-award",
    type: "award",
    iconName: "threekit.png",
    description:
      "Personal award from Threekit for the best-designed configurator UX for an external client (Lindsey Scoggins, a UK-based jeweller)",
    endDate: "2021-08-01",
    title: "Threekit",
    position: "User Experience Award",
  },
  {
    key: "greenhouse-fellowship",
    type: "award",
    iconName: "sortabase.png",
    description:
      "Personal award from Threekit for the best-designed configurator UX for an external client (Lindsey Scoggins, a UK-based jeweller)",
    endDate: "2017-04-01",
    title: "St. Paul's GreenHouse",
    position: "Big Ideas Fellowship",
    siteUrl: "https://www.facebook.com/ucgreenhouse/photos/t.100000728044944/1451231404952074",
  },
  {
    key: "toaster",
    type: "project",
    iconName: "toaster.png",
    description: "3D modelling tool that outputs pure HTML and CSS",
    endDate: "2023-05-01",
    title: "Toaster",
    bulletPoints: [<>Reached front page of Hacker News</>, <>200+ stars on Github</>],
    siteUrl: "https://petertyliu.github.io/toaster/",
    repoUrl: "https://github.com/PeterTYLiu/toaster",
    tools: ["Vite", "SASS", "TypeScript", "React", "Github Pages"],
  },
  {
    key: "xmorhic",
    type: "project",
    iconName: "xmorphic.png",
    description: "Phyisics-based hyperrealistic CSS shadow/gradient generator",
    endDate: "2023-04-01",
    title: "𝑥morphic.dev",
    siteUrl: "https://xmorphic.dev",
    repoUrl: "https://github.com/PeterTYLiu/xmorphic",
    tools: ["Vite", "SASS", "TypeScript", "React", "Github Pages"],
  },
  {
    key: "design-to-win-2019",
    type: "award",
    iconName: "sortabase.png",
    description: "Competed again in a UX design challenge against finalists selected from several hundred competitors",
    title: "Communitech Design to Win",
    position: "First Place",
    endDate: "2019-01-01",
    siteUrl: "https://communitech.ca/technews/waterloo-students-snag-top-prizes-at-code-design-to-win.html",
  },
  {
    key: "design-to-win-2018",
    type: "award",
    iconName: "sortabase.png",
    description: "Competed in a UX design challenge against finalists selected from several hundred competitors",
    title: "Communitech Design to Win",
    position: "Second Place",
    endDate: "2018-01-01",
    siteUrl: "https://www.facebook.com/photo/?fbid=1489278614522471",
  },
  {
    key: "carleton",
    type: "education",
    iconName: "sortabase.png",
    title: "Carleton University Full-Stack Bootcamp",
    description: "Completed a full-stack web development bootcamp at Carleton University while working full-time at Threekit.",
    location: "Ottawa",
    endDate: "2021-08-01",
    startDate: "2021-02-01",
    tools: ["React", "Node.js", "MongoDB", "Express.js", "Heroku", "Git"],
  },
  {
    key: "uwaterloo",
    type: "education",
    iconName: "sortabase.png",
    title: "University of Waterloo",
    position: "Bachelor of Environmental Studies, Joint Honours Urban Planning and Economics Co-op",
    description: "Completed a joint degree at the University of Waterloo, with several co-op work terms",
    bulletPoints: [<>President of UW Film Club</>, <>Member of UW Quizbowl competitive trivia team</>],
    endDate: "2018-12-01",
    startDate: "2013-09-01",
  },
];
